version: '3'
services:
  api:
    build:
      context: ./DTS_backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - agent_network
  front:
    build:
      context: ./DTS_frontend
      dockerfile: dockerfile
    ports:
      - 5173:5173
    networks:
      - agent_network
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"
    networks:
      - agent_network
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped 
    environment:
      - PGADMIN_DEFAULT_EMAIL=wulab@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ytwu35415
    ports:
      - "5555:80"
    networks:
      - agent_network
networks:
  agent_network:
